### ISSUE TITLE
USER STORY 3A: Product Searches

### ISSUE THREAD

**Issue by cardan22** [cardan22/bjorkhem#11]
As a **shopper**, I want to **quickly find products by using keywords** so that I can **easily locate the product I'm searching for.**

**Tasks:**
- [x] Integrate a responsive search bar.
- [x] Show products related to the search query.
- [x] Provide a clear count of the total search results.

**Acceptance Criteria:**
- [x] The search bar should provide real-time results as users input their queries.
- [x] The search results page must display relevant items, accompanied by a clear indication of the total result count.
