### ISSUE TITLE
USER STORY 5B: Edit/Update Product

### ISSUE THREAD

**Issue by cardan22** [cardan22/bjorkhem#19]
As an **admin**, I want **the capability to edit or update product information** so that I can **easily keep the webshop content up to date.**

**Tasks:**
- [x] Add a section in the admin panel where product details can be changed
- [x] Allow options to edit details like product name, description, and pricing.

**Acceptance Criteria:**
- [x] Admins should easily access and update product information in the admin panel.
- [x] Modifications to product details should show correctly on the webshop.
