### ISSUE TITLE
USER STORY 5C: Delete Product

### ISSUE THREAD

**Issue by cardan22** [cardan22/bjorkhem#20]
As an **admin**, I want to **delete items from the webshop** so that I can **keep track of inventory easily.**

**Tasks**
- [x] Add a feature in the admin panel to delete products.
- [x] Include confirmation prompts to avoid accidental deletions.

**Acceptance Criteria**
- [x] Admins should easily delete products through the admin panel.
- [x] Confirmation prompts should reduce the chance of accidental deletions.
