### ISSUE TITLE
USER STORY 1C: View Product Details

### ISSUE THREAD

**Issue by cardan22** [cardan22/bjorkhem#3]
As a **shopper**, I can **see specific details about a product** so that **I can make detailed purchase decisions**.

**Tasks:**
- [x] Design a page with all the important info about a product, including pictures, description, and price.
- [x] Make the page user-friendly for easy navigation and understanding of product features.

**Acceptance Criteria:**
- [x] Clicking on a product from the list leads to a dedicated page with all the details.
- [x] The product page displays high-quality pictures, a clear description, and the price.
- [x] Users can easily find and click on options like "Add to Cart" or "Buy Now."
