### ISSUE TITLE
USER STORY 1E: Responsive Design 

### ISSUE THREAD

**Issue by cardan22** [cardan22/bjorkhem#5]
As a **shopper**, I want **the website to work well on different devices** so I can **use it easily**.

**Tasks:**
- [x] Implement a responsive design framework.
- [x] Test the website on different devices and browsers.

**Acceptance Criteria:**
- [x] The website should work well on different screen sizes.
- [x] All features should work right on different web browsers
