### ISSUE TITLE
USER STORY 2D: Password Reset

### ISSUE THREAD

**Issue by cardan22** [cardan22/bjorkhem#9]
As a **user**, I want **an easy password reset process** so **I can quickly get back to my account.**

**Tasks:**
- [x] "Forgot Password"-link in login form.
- [x] Send a recovery email with link to reset password page.

**Acceptance Criteria:**
- [x] Utilise Allauth functionality to handle password reset option.
